"""remove a column

Revision ID: d9577e1188b3
Revises: c8bc9a25eb3a
Create Date: 2022-05-02 19:47:46.280281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9577e1188b3'
down_revision = 'c8bc9a25eb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_info', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
